### ISSUE TITLE
Working or not ?

### ISSUE THREAD

**Issue by ychoucha** [DC-SWAT/DreamShell#1]
So i have burn it and lunch it on my dreamcast, but no way to lunch the sd card ?
![Uploading IMG_2194.JPG . . .]()
![Uploading IMG_2195.JPG . . .]()
![img_2196](https://cloud.githubusercontent.com/assets/301074/5598917/6ca04f26-92be-11e4-8429-cc4d6ee5e5f3.JPG)

so i can lunch dreamShell, what is wrong ?

**Comment by DC-SWAT** [comment]
SD Card not detected? Try another SD card.
