### ISSUE TITLE
DreamShell bios loader currently broken with latest KOS.

### ISSUE THREAD

**Issue by MastaG** [DC-SWAT/DreamShell#36]
Just a reminder, so we can test once the problem has been fixed.

**Comment by MastaG** [comment]
(btw I subbed to your boosty page.. it aint much but it's something.. thanks for everything)

**Comment by DC-SWAT** [comment]
Fixed by KallistiOS update.

**Comment by MastaG** [comment]
Yes, I saw the commit in the KOS repository about the mutexes.
Thanks :)

When you have time, could you please test Quake3 Arena and check what makes the console reboot after the intro FMVs.
